workflows:
  main:
    name: Main Workflow
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Build iOS archive
        script: flutter build ios --release --no-codesign

      - name: Export IPA file
        script: flutter build ipa --release --export-options-plist exportOptions.plist

artifacts:
  - build/ios/ipa/*.ipa
